name: deploy-stminaconnect

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - 'marketing/**'
      - '.github/workflows/deploy-marketing.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger infrastructure deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRASTRUCTURE_PAT }}
          repository: markmorcos/infrastructure
          event-type: deploy-stminaconnect
          client-payload: |-
            {
              "repository": "markmorcos/stminaconnect",
              "token": "${{ secrets.DEPLOYMENT_TOKEN }}",
              "version": "${{ github.sha }}",
              "config_file": "marketing/deployment.yaml"
            }
